//  api
export const SETUP = 'api/SETUP'
export const SET_KEY = 'api/SET_KEY'
export const SET_REGION = 'api/SET_REGION'
export const ACHIEVEMENT = 'api/ACHIEVEMENT'
export const AUCTION_DATA_STATUS = 'api/AUCTION_DATA_STATUS'
export const ITEM = 'api/ITEM'
export const BOSS = 'api/BOSS'
export const CHARACTER_PROFILE = 'api/CHARACTER_PROFILE'
export const ZONE = 'api/ZONE'
export const RECIPE = 'api/RECIPE'
